module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Enchanted',
    'Majestic',
    'Whispering',
    'Mossy',
    'Golden',
    'Sapphire',
    'Eternal',
    'Whimsical',
    'Gentle',
    'Serenade',
    'Harmonious',
    'Crimson',
    'Emerald',
    'Serene',
    'Ivory',
    'Cascading',
    'Lush',
    'Tranquil',
    'Radiant',
    'Moonlit',
    'Azure',
    'Crystal',
    'Emergent',
    'Sacred',
    'Rustic',
    'Enigmatic',
    'Sunlit',
    'Celestial',
    'Amber',
    'Velvet',
    'Gentle',
    'Enveloping',
    'Bountiful',
    'Ethereal',
    'Velvet',
    'Gentle',
    'Enveloping',
    'Bountiful',
    'Ethereal',
    'Luminous',
    'Starlit',
    'Harmonic',
    'Silken',
    'Lavish',
    'Glistening',
    'Ample',
    'Pristine',
    'Tranquil',
    'Cerulean',
    'Resplendent',
    'Whistling',
    'Sylvan',
    'Twinkling',
    'Epic',
    'Mystical',
    'Hidden',
    'Aurora',
    'Lustrous',
    'Iridescent',
    'Verdant',
    'Solitude',
    'Harbor',
    'Ephemeral',
    'Enchanted',
    'Emergent',
    'Sapphire',
    'Crimson',
    'Divine',
    'Epic',
    'Sacred',
    'Awe-Inspiring',
    'Idyllic',
    'Cascading',
    'Ethereal',
    'Lavender',
    'Opulent',
    'Hushed',
    'Eternal',
    'Quaint',
    'Picturesque',
    'Epic',
    'Solemn',
    'Sapphire',
    'Vibrant',
    'Moss-Covered',
    'Blossoming',
    'Moonlit',
    'Serendipitous',
    'Blissful',
    'Elegiac',
    'Glorious',
    'Rippling',
    'Lush',
    'Singing',
    'Majestic',
    'Untamed',
    'Fabled',
    'Halcyon',
    'Surreal',
    'Echoing',
    'Radiant',
    'Mystifying',
    'Infinite',
    'Mythical',
    'Captivating',
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Meadow',
    'Grove',
    'Valley',
    'Lodge',
    'Peak',
    'Harbor',
    'Point',
    'Haven',
    'Glen',
    'Ridge',
    'Woods',
    'Hills',
    'Mist',
    'Brook',
    'Lagoon',
    'Isle',
    'Beach',
    'Dunes',
    'Plateau',
    'Pinnacle',
    'Oasis',
    'Summit',
    'Bluff',
    'Vista',
    'Hollow',
    'Shores',
    'Highlands',
    'Wilderness',
    'Enclave',
    'Estuary',
    'Sanctuary',
    'Inlet',
    'Gulf',
    'Terrace',
    'Parks',
    'Falls',
    'Cove',
    'Glade',
    'Prairie',
    'Aspen',
    'Foothills',
    'Savanna',
    'Ranch',
    'Wetlands',
    'Pines',
    'Timber',
    'Badlands',
    'Arbor',
    'Vineyards',
    'Quarry',
    'Trailhead',
    'Outpost',
    'Creekbed',
    'Thicket',
    'Crag',
    'Clearing',
    'Meadow',
    'Point',
    'Woods',
    'Brook',
    'Lagoon',
    'Isle',
    'Beach',
    'Dunes',
    'Plateau',
    'Pinnacle',
    'Oasis',
    'Shores',
    'Enclave',
    'Estuary',
    'Sanctuary',
    'Parks',
    'Cove',
    'Glade',
    'Prairie',
    'Aspen',
    'Foothills',
    'Savanna',
    'Ranch',
    'Wetlands',
    'Pines',
    'Timber',
    'Badlands',
    'Arbor',
    'Vineyards',
    'Riverside',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Valley',
    'Lodge',
    'Peak',
    'Harbor',
    'Haven',
    'Glen',
    'Ridge',
    'Hills',
]

module.exports.des = [
    "Amidst a field of wildflowers, a solitary butterfly flits gracefully from bloom to bloom, its delicate wings a vibrant burst of color.",
    "In a quaint coastal village, weathered cottages line the cobblestone streets, each one telling stories of generations past.",
    "Beneath the shimmering moonlight, a tranquil pond reflects the starry sky, creating a magical, mirror-like surface.",
    "At the heart of a bustling metropolis, a historic library stands as a sanctuary of knowledge, its shelves holding centuries of wisdom.",
    "Within a dense bamboo forest, a winding path leads to a hidden shrine, where ancient rituals are performed in quiet reverence.",
    "On a serene mountaintop, a solitary monastery clings to the cliffs, offering breathtaking vistas of the valleys below.",
    "Amidst rolling hills, a herd of wild horses gallops freely, their graceful movements a testament to the untamed spirit of nature.",
    "In a charming seaside town, fishermen gather at the harbor, sharing tales of their greatest catches beneath the warm coastal sun.",
    "Nestled in a picturesque valley, a quaint village square comes alive with the laughter of children playing and the aroma of freshly baked bread.",
    "Within the heart of a tropical rainforest, a majestic waterfall plunges into a crystal-clear pool, inviting weary travelers to refresh themselves.",
    "At the edge of a tranquil lake, a rustic cabin stands as a haven for solitude seekers, its flickering fireplace casting a cozy glow.",
    "Amidst a bustling bazaar, a street performer captivates the crowd with mesmerizing music, drawing passersby into a world of wonder.",
    "In a sunlit orchard, fruit-laden trees stretch as far as the eye can see, promising a bountiful harvest of sweetness and delight.",
    "On the cobbled streets of an ancient town, colorful market stalls offer handmade crafts and artisanal treasures from distant lands.",
    "Within a lush botanical garden, exotic flowers bloom in a riot of colors, releasing fragrant scents that enchant visitors.",
    "Perched on a rocky cliff, a solitary eagle soars high above, surveying the vast expanse of untouched wilderness below.",
    "Amidst a symphony of crickets and fireflies, a campfire crackles under the starry night, its warm glow inviting stories and camaraderie.",
    "In the heart of a vibrant city square, a grand fountain shoots water into the air, creating a mesmerizing dance of liquid sculpture.",
    "At the entrance to an ancient cave, intricate carvings and mysterious symbols hint at the secrets hidden within its depths.",
    "Nestled among rolling vineyards, a charming farmhouse offers a cozy retreat for wine enthusiasts, where every sip tells a story.",
    "Beside a tranquil riverside trail, a wooden bridge arches gracefully over the water, connecting two worlds with each step taken.",
    "In the heart of a bustling metropolis, a bustling street market teems with life, offering a sensory explosion of flavors, sights, and sounds.",
    "Deep within a mystical forest, a hidden waterfall reveals itself only to those who seek its elusive beauty, a secret oasis in the wilderness.",
    "In a charming coastal town, seagulls glide effortlessly over a sandy beach, while the salty breeze carries the distant sound of crashing waves.",
    "Within a bustling marketplace, colorful spices and exotic fruits create a vibrant tapestry of scents and flavors that tantalize the senses.",
    "Amidst a field of golden wheat, a scarecrow stands sentinel, its tattered clothes and straw hat guarding the precious harvest.",
    "On the banks of a serene river, a family of swans glides gracefully across the water, their reflection mirroring their elegance.",
    "In the heart of a medieval village, cobblestone streets wind through historic buildings, preserving the essence of a bygone era.",
    "Beneath a star-studded night sky, a campfire illuminates a group of friends sharing stories and laughter around its warm embrace.",
    "At the edge of a dense jungle, an ancient temple emerges from the lush foliage, its intricate carvings a testament to forgotten civilizations.",
    "Nestled in a verdant valley, a picturesque farmstead exudes rustic charm, with red barns and white picket fences under a blue sky.",
    "Within a vast desert, towering sand dunes shift and ripple in the scorching heat, creating an ever-changing landscape.",
    "Amidst the ruins of an old castle, ivy-clad stone walls evoke a sense of history, while the distant call of a lone owl adds an eerie ambiance.",
    "On a tranquil lake, a wooden rowboat glides silently, its oars barely disturbing the glassy surface, creating a sense of serenity.",
    "In the heart of a bustling city, a tranquil park offers a sanctuary of greenery, where urban dwellers seek refuge from the noise and chaos.",
    "Deep within a mystical forest, ancient toadstools form a whimsical fairy circle, shrouded in mystery and enchantment.",
    "Perched on a coastal cliff, a lighthouse stands tall, its rotating beacon cutting through the darkness, guiding ships safely to shore.",
    "Amidst a vibrant carnival, laughter fills the air as children enjoy carousel rides and indulge in cotton candy and colorful balloons.",
    "In a remote wilderness cabin, a crackling fireplace and a cozy blanket provide solace from the harsh winter cold outside.",
    "Amidst the ancient redwood trees' canopies, shafts of sunlight filter through, creating a dappling effect on the forest floor.",
    "In a remote desert oasis, palm trees provide shade and respite from the relentless sun, while a small pool offers a refreshing oasis's charm.",
    "On the banks of a winding river, a family of otters frolics in the water, their playful antics bringing smiles to onlookers's faces.",
    "Nestled among rolling vineyards, a rustic winery welcomes visitors to taste and savor the rich, velvety wines it produces's flavors.",
    "Within a bustling marketplace, artisans and craftsmen showcase their creations, their skilled hands molding raw materials into works of art's beauty.",
    "At the heart of a historic town square, a grand clock tower stands sentinel, its chimes marking the passage of time's hours.",
    "In a sun-kissed meadow, a field of sunflowers stretches towards the horizon, their golden petals reaching for the sky's warmth.",
    "Cascading down a rocky cliffside, a majestic waterfall crashes into a crystalline pool, its mist creating a cool, refreshing atmosphere's serenity.",
    "Amidst a dense tropical rainforest, colorful parrots and toucans dart through the canopy, their vibrant plumage a stunning contrast to the lush green foliage's brilliance.",
    "Under the star-studded night sky, a bonfire crackles and dances, casting flickering shadows on the faces of friends gathered around, sharing stories and laughter's joy.",
    "In a quaint seaside village, fishing boats bob gently in the harbor, while seagulls circle overhead, their cries echoing through the salty breeze's tranquility.",
    "Within the cozy confines of a mountain cabin, a roaring fireplace provides warmth, as snowflakes fall outside, blanketing the landscape in a peaceful hush's embrace.",
    "Inside a dimly lit cathedral, intricate stained glass windows cast a kaleidoscope of colors onto the stone floor, creating an aura of quiet reverence's solemnity.",
    "Beneath a clear, azure sky, a white-sand beach stretches out endlessly, the gentle waves lapping at the shore, inviting beachgoers to relax and unwind's charm.",
    "Within the bustling streets of a vibrant city, food vendors offer a tantalizing array of international cuisines, filling the air with mouthwatering aromas's allure.",
    "Amidst a field of lavender in full bloom, bees buzz busily, collecting nectar to create fragrant honey, while the air is filled with the soothing scent of lavender blossoms's beauty.",
    "At the edge of a serene mountain lake, a solitary rowboat waits, its oars resting on the calm water, as the surrounding peaks reflect in the glassy surface's tranquility.",
    "On the shores of a tranquil lake, a solitary swan glides gracefully across the water's surface, leaving a trail of ripples in its wake.",
    "In a quaint seaside village, the smell of fresh seafood wafts from the local fish market, enticing visitors with the promise of a delicious seafood feast.",
    "Within the confines of a historic library, an ancient tome with faded pages reveals the secrets of a bygone era, waiting for an eager scholar to uncover its mysteries.",
    "Amidst a field of blooming tulips, a gentle breeze causes the flowers to sway and dance, creating a vibrant sea of color.",
    "Beneath a canopy of twinkling stars, a telescope is pointed skyward, revealing distant galaxies and celestial wonders.",
    "On the cobblestone streets of an old European town, a street artist sketches a portrait of a curious passerby, capturing their essence in every stroke.",
    "Beside the roaring ocean's waves, a coastal lighthouse stands tall, guiding ships safely through the treacherous waters.",
    "In the heart of a bustling city's downtown, a historic theater's marquee lights up the night, announcing the latest blockbuster premiere.",
    "Within a quaint countryside village's square, a centuries-old oak tree provides shade and a gathering place for the community's residents.",
    "On the edge of a pristine wilderness's boundary, a ranger station serves as a hub for hikers and nature enthusiasts exploring the rugged terrain.",
    "Amidst a cluster of rocky hills, a hidden cave's entrance beckons adventurers to uncover its secrets and mysteries.",
    "Along the route of a scenic mountain road, a series of hairpin turns challenges drivers with breathtaking views of the valley below.",
    "Inside a centuries-old castle's stone walls, a medieval tapestry tells the story of a legendary knight's heroic deeds.",
    "In the midst of a bustling harbor's activity, a tall ship's crew raises the sails, preparing for a voyage to distant lands.",
    "Among a lush rainforest's lush greenery, a hidden waterfall's cascading waters create a serene oasis for weary travelers.",
    "Within a cozy cabin's warmth and comfort, a crackling fireplace's flames dance and flicker, casting a cozy glow.",
    "At the heart of a charming village's square, a historic well's moss-covered stones tell tales of generations past.",
    "Beneath a canopy of cherry blossom trees, a traditional tea ceremony's graceful movements and rituals unfold.",
    "Beside a tranquil river's banks, a solitary fisherman's patience is rewarded with a bountiful catch.",
    "In the depths of a mysterious cavern's darkness, a treasure hunter's lantern casts eerie shadows on ancient rock formations.",
    "Within the confines of a sprawling botanical garden's greenhouse, exotic orchids' vibrant colors and delicate shapes captivate visitors.",
    "Amidst a field of wildflowers, a gentle breeze's whisper carries the sweet scent of nature's blossoms.",
    "Inside a historic library's reading room, the hushed silence's tranquility encourages deep contemplation and exploration of knowledge.",
    "Along the course of a meandering river's twists and turns, a lone kayaker's paddle cuts through the water's surface with grace.",
    "In a remote mountain village's market square, the aroma of freshly baked bread fills the air, drawing hungry villagers to the bakery's doorstep.",
    "Beneath the towering skyscrapers of a bustling city's skyline, a rooftop garden's lush green oasis offers a peaceful escape from the urban hustle and bustle.",
    "Within the confines of an old castle's courtyard, a majestic peacock's vibrant plumage captures the attention of amazed onlookers.",
    "Amidst a field of lavender's vibrant hues, a gentle breeze's touch sets the fragrant flowers in motion, creating a mesmerizing sight.",
    "On the edge of a dense forest's depths, a hidden cabin's cozy hearth provides refuge from the cold and dark of the wilderness.",
    "Beside a tranquil lake's shore, a family of ducks' playful antics entertain spectators, adding a touch of whimsy to the serene scene.",
    "Within the lively atmosphere of a bustling bazaar's alleyway, a street performer's music and dance draw a captivated crowd.",
    "In a quaint coastal village's harbor, a fleet of fishing boats' arrival signals the beginning of the day's seafood catch.",
    "Along the cobbled streets of an old town's historic district, a vintage carriage's clip-clop echoes, transporting passengers to a bygone era.",
    "At the heart of a charming vineyard's estate, a centuries-old oak tree's sprawling branches provide shade for wine enthusiasts savoring their tastings.",
    "Within the confines of a picturesque garden's gazebo, a musician's gentle melodies create an enchanting ambiance for visitors.",
    "Beside a serene pond's edge, a family of turtles' sunbathe on a log, their slow movements adding a sense of tranquility to the scene.",
    "Amidst a vibrant coral reef's underwater world, a school of colorful fish's dart in and out of crevices, creating a mesmerizing spectacle.",
    "On the outskirts of a peaceful village's meadow, a group of children's laughter rings out as they play beneath the warm sun.",
    "Inside a cozy cottage's kitchen, the aroma of freshly baked apple pie's fills the air, inviting everyone to indulge in a slice.",
    "Within the grandeur of a majestic cathedral's nave, a choir's angelic voices resonate, lifting the spirits of all who gather for worship.",
    "Beside a picturesque waterfall's cascade, a rainbow's arch forms in the mist, adding a magical touch to the natural wonder.",
    "Along the path of a serene hiking trail's twists and turns, a family of deer's graze in a sun-dappled clearing, embodying the tranquility of the forest.",
];
