module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Enchanted',
    'Majestic',
    'Whispering',
    'Mossy',
    'Golden',
    'Sapphire',
    'Eternal',
    'Whimsical',
    'Gentle',
    'Serenade',
    'Harmonious',
    'Crimson',
    'Emerald',
    'Serene',
    'Ivory',
    'Cascading',
    'Lush',
    'Tranquil',
    'Radiant',
    'Moonlit',
    'Azure',
    'Crystal',
    'Emergent',
    'Sacred',
    'Rustic',
    'Enigmatic',
    'Sunlit',
    'Celestial',
    'Amber',
    'Velvet',
    'Gentle',
    'Enveloping',
    'Bountiful',
    'Ethereal',
    'Velvet',
    'Gentle',
    'Enveloping',
    'Bountiful',
    'Ethereal',
    'Luminous',
    'Starlit',
    'Harmonic',
    'Silken',
    'Lavish',
    'Glistening',
    'Ample',
    'Pristine',
    'Tranquil',
    'Cerulean',
    'Resplendent',
    'Whistling',
    'Sylvan',
    'Twinkling',
    'Epic',
    'Mystical',
    'Hidden',
    'Aurora',
    'Lustrous',
    'Iridescent',
    'Verdant',
    'Solitude',
    'Harbor',
    'Ephemeral',
    'Enchanted',
    'Emergent',
    'Sapphire',
    'Crimson',
    'Divine',
    'Epic',
    'Sacred',
    'Awe-Inspiring',
    'Idyllic',
    'Cascading',
    'Ethereal',
    'Lavender',
    'Opulent',
    'Hushed',
    'Eternal',
    'Quaint',
    'Picturesque',
    'Epic',
    'Solemn',
    'Sapphire',
    'Vibrant',
    'Moss-Covered',
    'Blossoming',
    'Moonlit',
    'Serendipitous',
    'Blissful',
    'Elegiac',
    'Glorious',
    'Rippling',
    'Lush',
    'Singing',
    'Majestic',
    'Untamed',
    'Fabled',
    'Halcyon',
    'Surreal',
    'Echoing',
    'Radiant',
    'Mystifying',
    'Infinite',
    'Mythical',
    'Captivating',
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Meadow',
    'Grove',
    'Valley',
    'Lodge',
    'Peak',
    'Harbor',
    'Point',
    'Haven',
    'Glen',
    'Ridge',
    'Woods',
    'Hills',
    'Mist',
    'Brook',
    'Lagoon',
    'Isle',
    'Beach',
    'Dunes',
    'Plateau',
    'Pinnacle',
    'Oasis',
    'Summit',
    'Bluff',
    'Vista',
    'Hollow',
    'Shores',
    'Highlands',
    'Wilderness',
    'Enclave',
    'Estuary',
    'Sanctuary',
    'Inlet',
    'Gulf',
    'Terrace',
    'Parks',
    'Falls',
    'Cove',
    'Glade',
    'Prairie',
    'Aspen',
    'Foothills',
    'Savanna',
    'Ranch',
    'Wetlands',
    'Pines',
    'Timber',
    'Badlands',
    'Arbor',
    'Vineyards',
    'Quarry',
    'Trailhead',
    'Outpost',
    'Creekbed',
    'Thicket',
    'Crag',
    'Clearing',
    'Meadow',
    'Point',
    'Woods',
    'Brook',
    'Lagoon',
    'Isle',
    'Beach',
    'Dunes',
    'Plateau',
    'Pinnacle',
    'Oasis',
    'Shores',
    'Enclave',
    'Estuary',
    'Sanctuary',
    'Parks',
    'Cove',
    'Glade',
    'Prairie',
    'Aspen',
    'Foothills',
    'Savanna',
    'Ranch',
    'Wetlands',
    'Pines',
    'Timber',
    'Badlands',
    'Arbor',
    'Vineyards',
    'Riverside',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Valley',
    'Lodge',
    'Peak',
    'Harbor',
    'Haven',
    'Glen',
    'Ridge',
    'Hills',
]

module.exports.des = [
    "Nestled in the heart of lush, emerald forests, this enchanting waterfall cascades gracefully, creating a serene oasis of natural wonder.",
    "A symphony of colors and fragrances, the vibrant botanical gardens transport visitors to a paradise of rare and exotic blooms.",
    "Perched atop a craggy cliff, the ancient castle's weathered stones whisper tales of bygone eras, offering breathtaking panoramic views of the surrounding countryside.",
    "With its cobblestone streets, charming cafes, and centuries-old architecture, this historic village is a picturesque time capsule where every corner tells a story.",
    "Sunset hues dance on the tranquil waters of the serene lake, casting a golden spell on all who come to witness nature's nightly spectacle.",
    "Wander through the aromatic fields of lavender, where a sea of purple blooms stretches to the horizon, creating a fragrant, soothing haven.",
    "The bustling marketplace is a kaleidoscope of sights and sounds, where artisans craft their wares, and the aroma of exotic spices fills the air.",
    "The ancient ruins, cloaked in moss and mystery, stand as a testament to the passage of time, inviting curious souls to explore their timeless secrets.",
    "Towering granite peaks pierce the heavens, their snow-capped summits glistening in the crisp mountain air, a playground for adventurers.",
    "Underneath the starlit sky, the tranquil beach unveils its own magic, where the gentle lullaby of waves serenades those who seek solace by the sea.",
];